---
title: "Philosophy of Science"
author: "Andrine Juvodden"
date: "Dato"
format:
  html:
    citation-style: resources/apa.csl.txt
bibliography: resources/idr-4000-referanser.bib
---

## Oppgave 1

**Ifølge Hume er det umulig å rasjonelt begrunne bruken av induksjon. Hva er argumentet for denne konklusjonen? Gi en innvending mot ett av premissene i Humes argument og prøv å svare på denne innvendingen på Humes vegne.**

David Hume var en filosof på 1700-tallet som blant annet er kjent for meningene sine om bruken av induksjon. Han mente det er umulig å rasjonelt begrunne bruken av induksjon og argumenterer for dette i all hovedsak ved å bruke to premisser: - All begrunnelse må enten være induktiv eller deduktiv - Hverken deduktiv eller induktiv begrunnelse kan rettferdiggjøre induksjon.

Det første premisset begrenser kunnskap til å stamme fra erfaring (induksjon) eller fornuften (deduksjon). Den induktive begrunnelsen gir kunnskap om verden basert på en antagelse om at fremtiden vil likne på fortiden. Den deduktive begrunnelsen gir sikker kunnskap, men begrenses til logiske sannheter.

Det andre premisset hevder verken induksjon eller deduksjon kan gi et klart grunnlag for å tro at induksjon er pålitelig. Induktivt blir et argument som er sirkulært, og deduktivt er det ikke mulig å bevise at fremtiden vil likne på fortiden.

Jeg har valgt abduksjon, som også er kalt «slutning til beste forklaring», som en innvending mot Humes argument. Abduksjon handler om å velge hypotesen som på best måte forklarer de observerte dataene. Hume kunne likevel argumentere for at abduksjon fortsatt er avhengig av induksjon. Skal vi vurdere hvilken hypotese som vil gi den beste forklaringen må vi gå ut ifra at fortidens mønstre vil fortsette i fremtiden.

Hvis vi for eksempel observerer at en plante trives i sollyset, kan vi abduktivt komme frem til at sollys er en nødvendighet for plantevekst. Imidlertid forutsetter denne konklusjonen at fremtidige planter vil reagere på samme måte på sollys, som de har gjort i fortiden, og dette er en antagelse som er induktiv.

Argumentet til Hume påpeker et grunnleggende problem i epistemologien. Hvordan kan vår tro på at fremtiden vil likne fortiden rettferdiggjøres? Selv om det ikke finnes et logisk bevis for dette, kan det argumenteres for at induksjon i praksis har vist seg å være en pålitelig metode. Evnen vår til å forutsi og kontrollere verden, fra hverdagslige handlinger til vitenskapelige oppdagelser, kan det tyde på at induksjon har en viss grad av gyldighet.

Poenget til Hume er ikke nødvendigvis at vi bør kutte bruken av induksjon. Han argumenterer for at vi må godta at induksjon ikke har et absolutt rasjonelt grunnlag. Kunnskapen vår om verden, basert på induksjon, er derfor alltid preget av en viss grad med usikkerhet.

## Oppgave 2

**Forklar de grunnleggende ideene i Bayesianisme, samt hvordan Bayesianske sannsynligheter kan tolkes. Presenter så ett problem med Bayesianisme og evaluer hvor alvorlig problemet er.**

Bayesianisme har blitt en svært populær tilnærming til statistikk of matematisk sannsynlighetsteori, basert på Bayes´ teorem (@Godfreysmith2003). Grunnlaget for Bayes Teorem og bayesianismen er filosof og statistiker, Thomas Bayes. Bayes teorem skrives som følger: Dette teoremet beskriver en metode for å oppdatere en «prior sannsynlighet» for en hypotese, gitt ny informasjon og data, for å få en «posterior sannsynlighet». Det handler altså om sannsynligheten for om en hendelse skal skje basert på tidligere observasjoner, det er dette som er kalt prior-sannsynlighet (@Godfreysmith2003). I slike analyser i Bayesianismen brukes nettopp denne tilnærmingen til å sannsynligjøre utfallet av en hendelse før ny data observeres. Etterhvert som ny informasjon blir tilgjengelig oppdateres den såkalte posterior-sannsynligheten, ved hjelp av Bayes Teorem. Dette betyr at man kan kontinuerlig regne seg frem til sannsynligheten for at noe skal skje. Hvis den nye informasjonen støtter den opprinnelige hypotesen, vil sannsynligheten for at dette skjer igjen øke, og vice versa.

Som følge av denne prosessen, vil en bayesianer sjelden hevde at noe er en absolutt sannhet, men heller gi uttrykk for hvor sannsynlig deet er å kunne tro på at noe er en sannhet, kun basert på matematiske utregninger. For eksempel kan dette bety at dersom tidligere forskning på et område er noe ambivalent, er et utfall 60% sannsynlig. Dersom ny forskning på området kommer på banen med data som støtter hypotesen, kan sannsynligheten for dette økes til eks. 80%. På denne måten oppdaterer man kunnskapen sin kontinuerlig og naturlig over tid.

En slik holistisk tilnærming til vitenskapen er sett på som en styrke med Bayesianismen, sammenlignet med for eksempel HD-metoden. Denne metoden baserer seg i stor grad på en binær tinærming til hypotese, som krever at en hypotese enten falsifiseres eller verifiseres gjennom testing. En utfordring ved HD-metoden er at den ikke tar noen høyder for usikkerheter eller andre gradvise endringer i forskningsfeltet. Derfor er Bayesianismen bedre egnet til å tolke slike endringer ved å tillate fleksibilitet i form av oppdaterte sannsynlighetsberegninger.

Selv om Bayesianisme gir en dynamisk og oppdatert forståelse på ulike forskningsspørsmål, har tilnærmingen også svakheter. Et problem er hvor man skal hente all den tidligere sannsynligheten fra, særlig når temaet er svakt representert i forskningsfeltet og har lite tidligere data å vise til. Temaer eller forskningsfelt det er svært lite data fra, som det er forsket lite på, er svært sårbare. Forskning av lav kvalitet eller begrenset omfang kan påvirke resultatene i stor grad, altså posterior-resultatene. Det kan tenkes at med mer informasjon og ny data vil dette utjevnes, men man skal være obs på at dette kan føre til skjevheter, bias. I tilfeller det det er gjort en del forskning på et tema kan det være en utfordring å få et klart bilde av prior-sannsynligheten, som kan føre til misvisende eller ufullstendige konklusjoner, men også at ulike personer kan bruke ulik prior-sannsynlighet for de samme eksperimentene (@K.Hackenberger2019) . Det er vanskelig å si noe om hvor store konsekvenser dette kan få, og det er nok avhengig av situasjonen.

Bayesianismen gir samlet sett en fleksibel tilnærming til forskningsspørsmål, men krever en nøye vurdering av hvilke data og tidligere sannsynligheter som brukes og legges til grunn for arbeidet. På en side gir metoden interessante muligheter til å utforske samme eksperiment med ulike prior-sannsynligheter og hypoteser justeres i takt med nye funn. På en annen side kan det være en utfordring å unngå subjektive valg som påvirker analysen.
